[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
progenitor = { path = "../../engine/progenitor" }
progenitor_server = { path = "../../engine/progenitor_server" }
async-trait = "0.1.58"
macro_rules_attribute = "0.1.3"

# TODO: Logger.
simple_logger = "4.0.0"