[package]
name = "progenitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
mongodb = "2.3.1"
tokio = "1.21.2"
async-trait = "0.1.58"
uuid = { version = "1.2.1", features = ["v4"] }
